"""
ai/explainer.py

Blockchain block explainer.
Uses OpenAI API when OPENAI_API_KEY is set in environment.
Falls back to a deterministic mock explanation when no key is configured.
This keeps the project fully functional offline / during demos.
"""

import os


def explain_block(block_data: dict) -> str:
    """
    Return a human-readable explanation of a block.
    Tries the real OpenAI API first; falls back to mock if key is absent.
    """
    api_key = os.getenv("OPENAI_API_KEY", "").strip()

    if api_key:
        return _openai_explain(block_data, api_key)
    else:
        return _mock_explain(block_data)


# ------------------------------------------------------------------
# Real OpenAI path  (OpenAI SDK v1+)
# ------------------------------------------------------------------
def _openai_explain(block_data: dict, api_key: str) -> str:
    try:
        from openai import OpenAI

        client = OpenAI(api_key=api_key)
        prompt = _build_prompt(block_data)

        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a blockchain analyst who explains blockchain data "
                        "clearly to developers and non-technical stakeholders."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
        )
        return response.choices[0].message.content

    except Exception as exc:
        # If the API call fails for any reason, fall back gracefully
        return _mock_explain(block_data) + f"\n\n[Note: OpenAI call failed — {exc}]"


# ------------------------------------------------------------------
# Mock explanation  (always works, no key required)
# ------------------------------------------------------------------
def _mock_explain(block_data: dict) -> str:
    block_index = block_data.get("block_index", "N/A")
    transactions = block_data.get("transactions", [])

    # Basic counts
    total_tx = len(transactions)
    regular_tx = [t for t in transactions if t.get("sender") != "MINER"]
    reward_tx  = [t for t in transactions if t.get("sender") == "MINER"]
    flagged_tx = [t for t in regular_tx if t.get("flagged", False)]

    total_volume = sum(float(t.get("amount", 0)) for t in regular_tx)
    miners = [t.get("recipient", "unknown") for t in reward_tx]

    lines = [
        f"=== Block #{block_index} — AI Explanation ===",
        "",
        f"This block contains {total_tx} transaction(s):",
        f"  • {len(regular_tx)} regular transfer(s) totalling {total_volume:.4f} CryptoSim coins.",
        f"  • {len(reward_tx)} mining reward(s) issued to: {', '.join(miners) if miners else 'none'}.",
        "",
    ]

    if flagged_tx:
        lines.append(
            f"⚠️  Fraud Alert: {len(flagged_tx)} transaction(s) in this block were "
            f"flagged as potentially suspicious by the ML model."
        )
        for t in flagged_tx:
            lines.append(
                f"   – Sender {t.get('sender', '?')} → Recipient {t.get('recipient', '?')} "
                f"| Amount: {t.get('amount', '?')} | Risk Score: {t.get('risk_score', 'N/A'):.4f}"
            )
        lines.append("")
    else:
        lines.append("✅  No transactions in this block were flagged as suspicious.")
        lines.append("")

    lines += [
        "Mining Context:",
        "  Each block is secured using Proof-of-Work. The miner solved a cryptographic",
        "  puzzle (finding a nonce such that the block hash starts with the required",
        "  number of leading zeros). This process makes the blockchain tamper-resistant.",
        "",
        "Digital Signatures:",
        "  Every regular transaction carries an ECDSA digital signature. The blockchain",
        "  verifies each signature before accepting a transaction, ensuring only the",
        "  rightful wallet owner can spend funds.",
        "",
        "Note: This explanation was generated by CryptoSim's built-in mock AI engine.",
        "Set the OPENAI_API_KEY environment variable to enable GPT-powered explanations.",
    ]

    return "\n".join(lines)


def _build_prompt(block_data: dict) -> str:
    return (
        f"Explain the following blockchain block in clear technical language. "
        f"Cover: what transactions occurred, whether any were flagged as fraudulent, "
        f"what the mining reward means, and the significance of digital signatures.\n\n"
        f"Block data:\n{block_data}"
    )
